# Generated by Django 4.0.4 on 2022-05-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wicker',
            name='author_name',
            field=models.CharField(default='author', max_length=255, verbose_name='Автор изделия'),
            preserve_default=False,
        ),
    ]
