# Generated by Django 4.0.4 on 2022-05-14 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_wicker_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWickerRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('in_bookmarks', models.BooleanField(default=False)),
                ('rate', models.PositiveSmallIntegerField(choices=[(1, 'Хорошая'), (2, 'Симпатичная'), (3, 'Классная'), (4, 'Удивительная'), (5, 'Отличная'), (6, 'Супер')], null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wicker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.wicker')),
            ],
        ),
    ]
